sudo: required

language: ruby

# env:
#   global:
#     - DOCKER_COMPOSE_VERSION=2

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker ps -a
  - sleep 5
  - docker logs dockeryii_app_1
  - ./test.sh

cache:
  directories:
    - docker
