sudo: required
language: ruby
env:
  global:
  - APP_ENV=development
  - DB_HOST=mysql
  - DB_PORT=3306
  - DB_NAME=yii
  - secure: nrj/y+9Z6FqFzfgJ8+arx/Kn9nq5WKLXIn6DBtQ+Qoo2Fc8Yfff2GZq/YMqnxSJaXHrt8xspulaJ24pqpPJvAnOJIY81cID1/Bte7xXy5JtIQwojp8ChhnLKjlUCQ70JFYHGpsd/2tKquqHahQkLTSKL23zgsDbAzRGSj5M/hgoT+9/0She6S3h/mEGxT6Ee0XtwWzqJp5c4lYYImWREF/LyeZJ1bnNc4qfOXw8NtFEhI4LXzYu9pyUp4ZOz69lG5dVvEksBvdZgrS3HtmByBuDhDRI1cCCjKmmWwkvtZPi/qg5qwfNvKCwt4fWT1k9UAKm5Q1s/dR3K5DsiZfINt1XtnFIy5lC9+Ea6Kudnftaw3+BuA384mtT+l0wnVB2I9VxIONd1fAoltsCaV0QVLy3WUp6Z4L2/aYhloYKyqk0ujsUAYaOIwuGBBgrVSXG/Yg1F6GEM7HvkwXO8Qbox9xssutULPARRPvqd+Eqb/+stBRwYcA84LVUfpkiMzAikLioHdzlJtEE1vVcUaalStMww20PqsVH+nIycQFb6EiCnYJ68SPndFl9vOetHWx7vI3TZsq5mfm2FKMkoKyo4QZkaBCXALa86ak9LIampE4/h15bS/g9yvwMmlUur+YrL04CXExvSU3zG9V/spRf6lUCanKJzVUcifnW0JANicSM=
  - secure: deFp5G6Ymk/vPD5AgoVrguh8Oq7Kfq5KfB55Io5z9wgqqOo1rFtbGe/kI3qXgM8n/7LXDQ2sbWifDXP7T9Fo9qc/W/PC5j0ZiFbCshNqgWoot5+vzR+wMLIUv9XAQPMJceqIMATJb+MzBi1wSjbrpJ2VX0VQqkmVgC2dyQZGHE7ZhKp+LVd9+jwh7kdCMxruON/DRex+g7hzNQW7Flrfm4ITJsynw/d5GjupzT2ZnvpHcUTbIFIiM84K24GZtG/9/XL3bj8kx7yiDydP/oyEEpRuogqVftrBQGWw83L7P4EwZiQ04FJsdgRYXF+pB9PwMGHvoxhgusp7nXK1M5r4j4ao8o4xwhgFJZWL1O17wlXBdwRZRSByVoJ445n/w7bd7kND89dvWiaKo0iAot6UEwVSfY9fMKI/Eof5g+iOleLimH6ikW/rNSU/fCWqw6I2s4NwU/RMQYNujuL8YNNHypC0QqFJFE6qCTFAveSMIQWxVcHJcGUj7OZ74Ntw8RgZtwLytzWcfohKdJg+TMUK0M3NCveRf49vj3iOI6gtCBvU1LH/pjCYxphHvcCeZtXqItN9CT0gV1vQaFt7UxBoeb1M9yGUlu8K2+0iahNnaiNpp6ltUT9K5n0tQm+2tbBEjR/6tBrrawNxMUQ4le1F4MOX4NdZXvPKZWjtrAQxEBs=
  - secure: uBmuD+FrSDNtgOGKK6OyzwmACzI2JgJmUsqAq6b9ojsob2sZUXVy7GlWMyVxh442D9xbsRUNRBvnG7tuZdqXyoQQHeHWVv1tYzy8x1Bb82jt/sJ2b4+dYGMsAy0XvChLJlRExB6TM45Xxnjzya2UouN/k8QsnW8TxXankP1IGd+QtyrWOi52GMt0tPlVyoGFknvR/l/q52jLJrjOyU35EAnBkeF13Jorggsh+f6XynUSBuShP9n3yWCuXfeYEY0jLKO0Wdnq9MgHrRjcObtwI3eZK0jLYe7auXcGQcHthydjSG4asfk+EWGeEZd2Pj0MVRA1tQfEEcN4aXv+wKkPEvlGFnDldmyAF1GPGvQRvKaAHZFrlYmUry5IGWkOe3ayqqegl7Q+eM6kR4tT6oBm1zLgz0hZQGGHEhsYU5PIjFpZQyxLkbx185ycuRBZYD2NXRXRo9aOmfB3DTLMmTT10rnwh53eOGyncvAQbja4U5ZkoCSBCFHSTq1H5huoNMgQ61fLbY4Eyia3mP+Ixcfd4BHwLEK9DbISHSko+aSZsSgx/KD2XaheIJJ4xjwosAXxZRvzU8jHmIAYGhLOBNiX6TkCgZVoaKGQbkaKe3jJh1rBWyJ4QShzArm4AqKISOVayerYL8S0PjlXGXapGb6l8toWNhwuABAj85L2DV+z39U=
  - secure: ymNKq8lSRM7h/0sJbMBWdyAGGoKfBjifmVDxWvbV8nZzlwKVE8fNJecJMC3nMiF6llryAO7LJx3aEybaiDw2lWGXH/QGg4tPsx6kSFkpbCFHb3Ta4t2PW48wUL8P0DWe8prjtEQeEwoOqpjmE3vNStRycEktYkJY1jXZvFDwLOp0ZCfZJQGoRUSqYT/TTZDdHYtp7K2LWSSxjPon6/y+MzE6uwEDWzVlf6qNO/UF7Hiv7qz10Yez4KUI/jfdLfdhA3YPtlyygh7MNh0lBYBercTbJ0yYtdzZstTHqON8iR/Asi1jsiMV0wbTPPZFJJPp8tkmjjw2hNzVyLym1U/Q8OnTafSo0O5D2MRfCNM/6XdTkboetp5VW5lvK7iyIXgIsSdNX6vO0ULDVi52ToDXNbToQa7EO7/NpAC+gTFzYhu7YqkU7tVK+4hDlvv39NwkJQG0FqgHSuzguamvnqqTDMIbJU1sZjbTVC3M1MOe99HYoqoGmwIdd6c6BaHK52wtvDPapS6DWlic6KxKPbPiCGlqXW6xCm0cX9VclrrCsMWwcxGRoNcfIb2qjZ0VchwqmuzK2U5dDhUWJPmJ8sUJtgnFwmBj27XigWN/7uuVDYL9Hi4w8CYAHiSdr+bst4ZMww37uF1KvmdAO1ZpDgujA4BdiehhxQ8XGi6sLOnFcLI=
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
script:
- docker ps -a
# - sleep 5
- docker logs dockeryii_app_1
- docker logs dockeryii_nginx_1
- docker logs dockeryii_mysql_1
- "./test.sh"
cache:
  directories:
  - docker
