sudo: required

language: ruby

# env:
#   global:
#     - DOCKER_COMPOSE_VERSION=2

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d

script:
  - ./wait-for-it.sh 127.0.0.1:80 --strict --timeout=60 && ./test.sh

cache:
  directories:
    - docker
