version: '2'

services:
  mysql:
    image: mysql:5.6
    env_file:
      - .yii.env
    volumes:
      - mysql:/var/lib/mysql
      
  app:
    build: .
    volumes:
      - ./src:/var/www/html
    env_file:
      - .yii.env
    depends_on:
      - mysql
  
  nginx:
    build: ./nginx/
    ports:
      - '80:80'
    volumes:
      - ./src/web:/var/www/html/web
    depends_on:
      - app

volumes:
  mysql: