version: '2'

services:
  mysql:
    image: mysql:5.6
    env_file:
      - .yii.env
    volumes:
      - mysql:/var/lib/mysql
      
  app:
    build: .
    volumes:
      - ./src:/var/www/html
    env_file:
      - .yii.env
    depends_on:
      - mysql
  
  nginx:
    image: cmr1/nginx-proxy:php-fpm
    env_file:
      - .yii.env
    ports:
      - '80:80'
    volumes_from:
      - app
    depends_on:
      - app

volumes:
  mysql: